name: Keep Hugging Face Space Alive with Alert

on:
  schedule:
    # Chạy mỗi 30 phút
    - cron: "*/30 * * * *"
  workflow_dispatch: # Chạy thủ công nếu cần

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hugging Face Space
        run: |
          SPACE_URL="https://kawaiicassie-n8n.hf.space"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$SPACE_URL" || echo "000")

          echo "HTTP Status: $RESPONSE"

          if [ "$RESPONSE" != "200" ]; then
            MESSAGE="🚨 Hugging Face Space có thể đang ngủ hoặc lỗi! Mã trả về: $RESPONSE"
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
              -d text="$MESSAGE"
          else
            echo "✅ Space đang hoạt động bình thường."
          fi
